#ifndef TUNES_H
#define TUNES_H

//App Tunes
#define I2S_SAMPLE_RATE 44100
#define MAX_VISUALIZATION_FREQUENCY 4000.0
#define I2S_BUFFER_COUNT 30
#define I2S_SAMPLE_COUNT 128
#define NUMBER_OF_BANDS 32
#define FFT_SIZE 1024

#endif TUNES_H
